### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Cypher1** [termhn/i3-vim-nav#4]
Seems that this depends on xdotool and maybe some other packages.
As such I have not quite been able to get it working or been able to work out all dependencies needed.
Could you update the readme?

Thanks

**Comment by fu5ha** [comment]
Yep. It should just be xdotool. Added a section to the readme in #5. Are you getting errors when trying to execute the command from a terminal or just when executing from your i3 config? I just switched my distro and am having trouble with the latter--I added a section at the bottom of the readme about it that you might try if you're having a similar issue.

**Comment by Cypher1** [comment]
Not sure what the issue is now, I have checked that I have xdotool, libxdo-dev and even go installed and I haven't been able to get the mapping working inside neovim or moving from a window to a neovim split (the previously selected split it always chosen).

Any ideas? i3-vim-nav executes and I can move between some windows (running it via shell or hot key). There is no error output.

**Comment by fu5ha** [comment]
I had that issue for a long time and finally solved it with the `--release` option on the bindsym command. 

Does it work if you run
```
sleep 5; i3-msg exec "i3-vim-nav l"
```
And then move your mouse into neovim before it executes? If not, does it work if you run 
```
sleep 5; xdotool key --clearmodifiers "Escape+control+l"
```
and then do the same thing?

**Comment by Cypher1** [comment]
Using i3-msg I get sent to the next window. With xdotool I get sent to the next character (in the current split).

Thanks

**Comment by fu5ha** [comment]
Hmm. And you're using `bindsym --release` in your i3 config? Not sure. What version of i3 are you using?

**Comment by Cypher1** [comment]
Yup, copied and pasted the settings.

I'm on 4.11.

**Comment by Cypher1** [comment]
Could it be something to do with my neovim setup?

**Comment by fu5ha** [comment]
Huh. I'm not sure. It seems to me that if it works on delay with i3-msg then it would be something to do with the way the hotkey is being triggered specifically, aka i3, though I could be totally off base on that. Any reason you aren't on the latest version of i3? I think 4.11 would have had the --release functionality as well, but I'm not sure.

**Comment by Cypher1** [comment]
I'm not sure that it's even working via i3-msg though. I can't change
splits with any of it.

I'm on 4.11 because that's the latest available version on my distro
(Mint), I haven't been checking for external updates.

**Comment by fu5ha** [comment]
Ah, I see, guess I misunderstood your meaning. 
And you said that
```
sleep 3; xdotool key --clearmodifiers "Escape+control+l"
```
doesn't work either? Does just pressing the hotkey (`<C-l|h|j|k>`) in vim work?

**Comment by Cypher1** [comment]
The above command moves the cursor right one character.
The hotkey still moves focus to the next window (but ignores splits entirely).

**Comment by fu5ha** [comment]
Huh. That's definitely weird. I'm not sure, I'll think about it though and let you know if I think of anything.

**Comment by Cypher1** [comment]
That's, still, it may be time for me to set up my GOPATH and play with
debugging the go and vimscript side by side.

**Comment by fu5ha** [comment]
Yeah. If you figure out a solution, feel free to make a new issue/submit a PR.
