### ISSUE TITLE
Doesn't work on Neovim

### ISSUE THREAD

**Issue by cjbassi** [termhn/i3-vim-nav#6]
Not working for me with Neovim, because Neovim doesn't change the window name when running like Vim does. Are there any workaround to this or is this something that would need to be fixed on Neovim's end?

**Comment by fu5ha** [comment]
I believe this is an artifact of your terminal emulator, not Neovim itself. In terminator (my preferred terminal emulator), it changes the title to the name of the current process. The main way you could work around this is if you can get the title to change in an at all meaningful manner when you're in vim--or if you could open a different terminal window specifically for using vim--and then edit the regex expression in the go code (https://github.com/termhn/i3-vim-nav/blob/master/i3-vim-nav.go#L26) to match with whatever that unique change is.

**Comment by cjbassi** [comment]
Hmm something funky is going on with my setup. Termite, xterm, and urxvt all change the window name with Vim, but not with Neovim. And with Terminator, the window name doesn't change at all and just says 'zsh'. I'll play around with it some more and try one of your suggestions if it doesn't start working. Thanks for the advice.

**Comment by fu5ha** [comment]
Hm. Perhaps it has to do with your shell as well then? I'm using fish
personally.

**Comment by cjbassi** [comment]
I'm currently using zsh, but I'm not sure if that's the issue. Either way, I ended up just opening Neovim in it's own terminal window with a custom window name, that should work for now. Will update for posterity if I ever figure out what the issue was. Thanks for your help btw.
